spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:
    topic: transaction-topic
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest
      properties:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.trusted.packages: com.model.TransactionEvent

    producer:
      properties:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
services:
  ledger:
    url: http://localhost:8081/api/ledger
  balance:
    url: http://localhost:8082/api/balance


server:
  port: 8080
