logging:
  level:
    root: INFO
    org.springframework: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081
